<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Noticias;

/**
 * NoticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Función que devuelve todas las noticias
     * @return array
     */
    public function getNoticias()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT n
             FROM AppBundle\Entity\Noticias n
             WHERE n.idCurso IN 
             (SELECT c.grupo 
             FROM AppBundle\Entity\Cursos c) ORDER BY n.id ASC'
        );

        return $query->getResult();

    }
}
