<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2v0cey0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2v0cey0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2v0cey0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2v0cey0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2v0cey0\appDevDebugProjectContainer();
